<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5OD0AA6" failures="5" tests="29" name="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" time="258.825" errors="0" timestamp="2025-01-08T21:40:52 CET" skipped="0">
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.199"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.274"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.291"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.372"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.291"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.380"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.511"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.779"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.363"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="5.714">
    <failure message="****The user registered on the site despite incorrect data ****" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ****The user registered on the site despite incorrect data ****
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_002_ValidationOfIncorrectRegistration_TDD.ValidationOfIncorrectRegistration_TDD(TC_002_ValidationOfIncorrectRegistration_TDD.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
    </failure>
  </testcase> <!-- ValidationOfIncorrectRegistration_TDD -->
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="5.960">
    <failure message="****The user registered on the site despite incorrect data ****" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ****The user registered on the site despite incorrect data ****
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_002_ValidationOfIncorrectRegistration_TDD.ValidationOfIncorrectRegistration_TDD(TC_002_ValidationOfIncorrectRegistration_TDD.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
    </failure>
  </testcase> <!-- ValidationOfIncorrectRegistration_TDD -->
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.590"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.402"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.193"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.116"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.814"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="10.046"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.323"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="6.238">
    <failure message="****The user registered on the site despite incorrect data ****" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ****The user registered on the site despite incorrect data ****
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_002_ValidationOfIncorrectRegistration_TDD.ValidationOfIncorrectRegistration_TDD(TC_002_ValidationOfIncorrectRegistration_TDD.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
    </failure>
  </testcase> <!-- ValidationOfIncorrectRegistration_TDD -->
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.238"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.123"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="5.730">
    <failure message="****The user registered on the site despite incorrect data ****" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ****The user registered on the site despite incorrect data ****
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_002_ValidationOfIncorrectRegistration_TDD.ValidationOfIncorrectRegistration_TDD(TC_002_ValidationOfIncorrectRegistration_TDD.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
    </failure>
  </testcase> <!-- ValidationOfIncorrectRegistration_TDD -->
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.198"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="13.535"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.292"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.338"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.555"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="9.277"/>
  <testcase classname="testCases.TC_002_ValidationOfIncorrectRegistration_TDD" name="ValidationOfIncorrectRegistration_TDD" time="5.683">
    <failure message="****The user registered on the site despite incorrect data ****" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ****The user registered on the site despite incorrect data ****
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_002_ValidationOfIncorrectRegistration_TDD.ValidationOfIncorrectRegistration_TDD(TC_002_ValidationOfIncorrectRegistration_TDD.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
    </failure>
  </testcase> <!-- ValidationOfIncorrectRegistration_TDD -->
</testsuite> <!-- testCases.TC_002_ValidationOfIncorrectRegistration_TDD -->
